import { useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { Separator } from '@/components/ui/separator';
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';
import {
  AlertTriangle,
  Shield,
  ExternalLink,
  MessageSquare,
  Target,
  Github,
} from 'lucide-react';
import { getSeverityClasses, getSeverityStripeClass, getStatusClasses } from '@/lib/risk';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';
import { jiraApi } from '@/lib/api';
import JiraIssuePreviewDialog from '@/components/JiraIssuePreviewDialog';

interface ThreatData {
  id: number;
  status: string;
  comments: string;
  severity: 'low' | 'medium' | 'high' | 'critical' | null;
  risk_score: number | null;
  acceptance_justification?: string | null;
  threat: {
    name: string;
    description: string;
    category: string;
  };
}

interface MitigationData {
  id: number;
  status: string;
  comments: string;
  mitigation: {
    name: string;
    description: string;
    category?: string;
  };
}

interface ContextItem {
  icon: React.ReactNode;
  label: string;
}

interface ThreatCardProps {
  threat: ThreatData;
  linkedMitigations: MitigationData[];
  contextItems?: ContextItem[];
  index?: number;
  repoUrl?: string | null;
  jiraConfigured?: boolean;
  /** Product-level default Jira project key (fed into the preview dialog) */
  jiraProjectKey?: string | null;
  onOpen: () => void;
  onNavigateToDiagram?: () => void;
}

function buildGitHubIssueUrl(repoUrl: string, threat: ThreatData, mitigations: MitigationData[]): string {
  // Accept https://github.com/owner/repo or https://github.com/owner/repo.git
  const match = repoUrl.match(/github\.com\/([^/]+\/[^/]+?)(?:\.git)?(?:\/|$)/);
  if (!match) return '';
  const slug = match[1];
  const title = `[Security] ${threat.threat.name}`;
  const mitList = mitigations.length
    ? mitigations.map(m => `- [ ] ${m.mitigation.name} *(${m.status})*`).join('\n')
    : '_No mitigations linked yet._';
  const body = [
    `## Security Threat: ${threat.threat.name}`,
    '',
    `**Category:** ${threat.threat.category}`,
    `**Severity:** ${threat.severity ?? 'unscored'}`,
    `**Risk Score:** ${threat.risk_score ?? '—'}`,
    `**Status:** ${threat.status}`,
    '',
    '### Description',
    threat.threat.description || '_No description._',
    '',
    '### Mitigations',
    mitList,
    '',
    '---',
    '_Generated by [ThreatAtlas](https://github.com/OWASP/www-project-threatatlas)_',
  ].join('\n');
  return `https://github.com/${slug}/issues/new?title=${encodeURIComponent(title)}&body=${encodeURIComponent(body)}&labels=security`;
}


function getMitigationProgress(mitigations: MitigationData[]): number {
  if (mitigations.length === 0) return 0;
  const done = mitigations.filter(m => m.status === 'implemented' || m.status === 'verified').length;
  return Math.round((done / mitigations.length) * 100);
}

function severityToJiraPriority(severity: ThreatData['severity']): string {
  switch (severity) {
    case 'critical': return 'Critical';
    case 'high': return 'High';
    case 'low': return 'Low';
    case 'medium':
    default: return 'Medium';
  }
}

export default function ThreatCard({
  threat,
  linkedMitigations,
  contextItems,
  index = 0,
  repoUrl,
  jiraConfigured = false,
  jiraProjectKey,
  onOpen,
  onNavigateToDiagram,
}: ThreatCardProps) {
  const [jiraDialogOpen, setJiraDialogOpen] = useState(false);

  // ── Build the Jira preview payload ────────────────────────────────────────
  const jiraSummary = `[Security] ${threat.threat.name}`;
  const jiraDescription = (() => {
    const mitList = linkedMitigations.length
      ? linkedMitigations.map(m => `• ${m.mitigation.name} (${m.status})`).join('\n')
      : '(none)';
    return [
      `Category: ${threat.threat.category}`,
      `Severity: ${threat.severity ?? 'unscored'}`,
      `Risk Score: ${threat.risk_score ?? '—'}`,
      `Status: ${threat.status}`,
      '',
      'Description:',
      threat.threat.description || '(none)',
      '',
      'Mitigations:',
      mitList,
      '',
      '---',
      'Generated by ThreatAtlas',
    ].join('\n');
  })();

  const handleConfirmJiraIssue = async (summary: string, description: string, projectKey: string) => {
    const r = await jiraApi.createIssue({
      summary,
      description,
      issue_type: 'Bug',
      priority: severityToJiraPriority(threat.severity),
      threat_id: threat.id,
      project_key: projectKey,
    });
    toast.success(
      `Jira issue ${r.data.key} created`,
      { action: { label: 'Open', onClick: () => window.open(r.data.url, '_blank') } }
    );
  };

  const githubUrl = repoUrl ? buildGitHubIssueUrl(repoUrl, threat, linkedMitigations) : '';

  const mitigationProgress = getMitigationProgress(linkedMitigations);
  const hasComments = threat.comments && threat.comments !== '[]';

  const getIconColor = () => {
    if (threat.status === 'mitigated') return 'var(--element-mitigation)';
    if (threat.status === 'accepted') return 'var(--ds-stone-gray)';
    if (linkedMitigations.length === 0) return 'var(--element-threat)';
    return 'var(--element-removal)';
  };

  return (
    <Card
      className="animate-fadeInUp hover:shadow-lg hover:border-primary/20 transition-all duration-300 rounded-xl relative overflow-hidden py-0"
      style={{ animationDelay: `${index * 40}ms` }}
    >
      {/* Severity stripe */}
      <div aria-hidden="true" className={cn('absolute left-0 top-0 bottom-0 w-1', getSeverityStripeClass(threat.severity))} />

      <CardContent className="p-0">
        {/* ── Threat section ── */}
        <div className="px-5 pl-6 pt-2 pb-1 cursor-pointer group/threat" onClick={onOpen}>
          {/* Top bar: icon + name + badges + actions */}
          <div className="flex items-center gap-3 mb-2">
            <div
              className="flex h-9 w-9 items-center justify-center rounded-lg shrink-0"
              style={{ backgroundColor: `color-mix(in srgb, ${getIconColor()} 10%, transparent)` }}
            >
              <AlertTriangle className="h-4 w-4" style={{ color: getIconColor() }} />
            </div>
            <h3 className="font-medium text-sm leading-snug group-hover/threat:text-primary transition-colors flex-1 min-w-0 truncate">
              {threat.threat.name}
            </h3>
            <div className="flex items-center gap-1.5 shrink-0">
              {threat.severity && (
                <Badge variant="outline" className={cn('capitalize text-[11px]', getSeverityClasses(threat.severity))}>
                  {threat.severity}
                </Badge>
              )}
              {threat.status === 'accepted' && threat.acceptance_justification ? (
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Badge variant="outline" className={cn('capitalize text-[11px]', getStatusClasses(threat.status))}>
                      {threat.status}
                    </Badge>
                  </TooltipTrigger>
                  <TooltipContent className="max-w-xs">
                    <p className="text-xs font-semibold mb-0.5">Acceptance Justification</p>
                    <p className="text-xs">{threat.acceptance_justification}</p>
                  </TooltipContent>
                </Tooltip>
              ) : (
                <Badge variant="outline" className={cn('capitalize text-[11px]', getStatusClasses(threat.status))}>
                  {threat.status}
                </Badge>
              )}
              {threat.risk_score !== null && (
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Badge variant="secondary" className="text-[11px] font-mono tabular-nums gap-1 cursor-default">
                      <Target className="h-3 w-3 shrink-0" />
                      {threat.risk_score}
                    </Badge>
                  </TooltipTrigger>
                  <TooltipContent>Risk score</TooltipContent>
                </Tooltip>
              )}
              {hasComments && (
                <MessageSquare className="h-3 w-3 text-muted-foreground/50" />
              )}
              {onNavigateToDiagram && (
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-7 w-7 p-0 shrink-0 opacity-0 group-hover/threat:opacity-100 hover:bg-primary/10 rounded-lg transition-all"
                      aria-label="View in diagram"
                      onClick={(e) => { e.stopPropagation(); onNavigateToDiagram(); }}
                    >
                      <ExternalLink className="h-3.5 w-3.5" />
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>View in diagram</TooltipContent>
                </Tooltip>
              )}

              {/* GitHub icon — only when repo URL is configured */}
              {githubUrl && (
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-7 w-7 p-0 shrink-0 opacity-0 group-hover/threat:opacity-100 hover:bg-primary/10 rounded-lg transition-all"
                      aria-label="Create GitHub issue"
                      onClick={(e) => e.stopPropagation()}
                      asChild
                    >
                      <a href={githubUrl} target="_blank" rel="noopener noreferrer">
                        <Github className="h-3.5 w-3.5" />
                      </a>
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>Create GitHub issue</TooltipContent>
                </Tooltip>
              )}

              {/* Jira icon — only when Jira integration is configured */}
              {jiraConfigured && (
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-7 w-7 p-0 shrink-0 opacity-0 group-hover/threat:opacity-100 hover:bg-[#2684FF]/10 rounded-lg transition-all"
                      aria-label="Create Jira issue"
                      onClick={(e) => { e.stopPropagation(); setJiraDialogOpen(true); }}
                    >
                      <img src="/images/ticketing/jira.svg" alt="Jira" className="h-3.5 w-3.5" />
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>Create Jira issue</TooltipContent>
                </Tooltip>
              )}

            </div>
          </div>

          <p className="text-xs text-muted-foreground leading-relaxed line-clamp-2 mb-2">
            {threat.threat.description}
          </p>

          {/* Bottom meta row: category + context */}
          <div className="flex items-center gap-2 text-[11px] text-muted-foreground flex-wrap pb-1">
            <Badge variant="outline" className="text-[10px]">{threat.threat.category}</Badge>
            {contextItems && contextItems.length > 0 && (
              <>
                <span className="text-border/60">&middot;</span>
                {contextItems.map((item, i) => (
                  <span key={i} className="flex items-center gap-1">
                    {i > 0 && <span className="text-border/60">&middot;</span>}
                    {item.icon}
                    <span>{item.label}</span>
                  </span>
                ))}
              </>
            )}
            {linkedMitigations.length > 0 && (
              <>
                <span className="text-border/60">&middot;</span>
                <span className="inline-flex items-center gap-1.5">
                  <Shield className="h-3 w-3" style={{ color: 'var(--risk-low)' }} />
                  <span className="font-medium">{linkedMitigations.length} Mitigation{linkedMitigations.length > 1 ? 's' : ''}</span>
                </span>
                <div className="inline-flex items-center gap-2">
                  <Progress value={mitigationProgress} className="h-1 w-16" />
                  <span className="tabular-nums">{mitigationProgress}%</span>
                </div>
              </>
            )}
          </div>
        </div>

        {/* ── Mitigations chips ── */}
        {linkedMitigations.length > 0 && (
          <>
            <Separator className="opacity-50" />
            <div
              className="bg-muted/15 px-5 pl-6 py-3 cursor-pointer"
              onClick={onOpen}
            >
              <div className="flex flex-wrap gap-2">
                {linkedMitigations.map((mit) => (
                  <div
                    key={mit.id}
                    className="flex items-center gap-2 px-2.5 py-1.5 rounded-lg border bg-background/60 hover:bg-background hover:shadow-sm transition-all text-xs"
                  >
                    <Shield
                      className="h-3.5 w-3.5 shrink-0"
                      style={{
                        color: mit.status === 'verified'
                          ? 'var(--risk-low)'
                          : mit.status === 'implemented'
                          ? 'var(--matcha-300)'
                          : undefined,
                      }}
                    />
                    <div className="flex flex-col min-w-0 max-w-[180px]">
                      <span className="font-medium truncate leading-tight">{mit.mitigation.name}</span>
                      {mit.mitigation.category && (
                        <span className="text-[10px] text-muted-foreground truncate leading-tight">{mit.mitigation.category}</span>
                      )}
                    </div>
                    <Badge variant="outline" className={cn('text-[10px] px-1.5 py-0 capitalize shrink-0 ml-auto', getStatusClasses(mit.status))}>
                      {mit.status}
                    </Badge>
                    {mit.comments && mit.comments !== '[]' && (
                      <MessageSquare className="h-3 w-3 text-muted-foreground/50 shrink-0" />
                    )}
                  </div>
                ))}
              </div>
            </div>
          </>
        )}
      </CardContent>

      {/* Jira issue preview dialog */}
      <JiraIssuePreviewDialog
        open={jiraDialogOpen}
        onOpenChange={setJiraDialogOpen}
        initialSummary={jiraSummary}
        initialDescription={jiraDescription}
        priority={severityToJiraPriority(threat.severity)}
        defaultProjectKey={jiraProjectKey}
        onConfirm={handleConfirmJiraIssue}
      />
    </Card>
  );
}
