"""add_diagram_versioning

Revision ID: 1e4c215959d3
Revises: de84307a6882
Create Date: 2026-02-13 19:32:23.339936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e4c215959d3'
down_revision: Union[str, Sequence[str], None] = 'de84307a6882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagram_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagram_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('diagram_data', sa.JSON(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['diagram_id'], ['diagrams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagram_id', 'version_number', name='uq_diagram_version')
    )
    op.create_index(op.f('ix_diagram_versions_diagram_id'), 'diagram_versions', ['diagram_id'], unique=False)
    op.create_index(op.f('ix_diagram_versions_id'), 'diagram_versions', ['id'], unique=False)
    op.create_index(op.f('ix_diagram_versions_version_number'), 'diagram_versions', ['version_number'], unique=False)
    op.create_table('diagram_threat_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('diagram_threat_id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.String(length=100), nullable=False),
    sa.Column('element_type', sa.String(length=50), nullable=False),
    sa.Column('threat_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('likelihood', sa.Integer(), nullable=True),
    sa.Column('impact', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagram_threat_id'], ['diagram_threats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_id'], ['threats.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['diagram_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagram_threat_versions_diagram_threat_id'), 'diagram_threat_versions', ['diagram_threat_id'], unique=False)
    op.create_index(op.f('ix_diagram_threat_versions_id'), 'diagram_threat_versions', ['id'], unique=False)
    op.create_index(op.f('ix_diagram_threat_versions_threat_id'), 'diagram_threat_versions', ['threat_id'], unique=False)
    op.create_index(op.f('ix_diagram_threat_versions_version_id'), 'diagram_threat_versions', ['version_id'], unique=False)
    op.create_table('diagram_mitigation_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('diagram_mitigation_id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.String(length=100), nullable=False),
    sa.Column('element_type', sa.String(length=50), nullable=False),
    sa.Column('mitigation_id', sa.Integer(), nullable=False),
    sa.Column('threat_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagram_mitigation_id'], ['diagram_mitigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mitigation_id'], ['mitigations.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['diagram_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagram_mitigation_versions_diagram_mitigation_id'), 'diagram_mitigation_versions', ['diagram_mitigation_id'], unique=False)
    op.create_index(op.f('ix_diagram_mitigation_versions_id'), 'diagram_mitigation_versions', ['id'], unique=False)
    op.create_index(op.f('ix_diagram_mitigation_versions_mitigation_id'), 'diagram_mitigation_versions', ['mitigation_id'], unique=False)
    op.create_index(op.f('ix_diagram_mitigation_versions_version_id'), 'diagram_mitigation_versions', ['version_id'], unique=False)
    op.add_column('diagrams', sa.Column('current_version', sa.Integer(), server_default='0', nullable=False))
    op.add_column('diagrams', sa.Column('auto_version', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagrams', 'auto_version')
    op.drop_column('diagrams', 'current_version')
    op.drop_index(op.f('ix_diagram_mitigation_versions_version_id'), table_name='diagram_mitigation_versions')
    op.drop_index(op.f('ix_diagram_mitigation_versions_mitigation_id'), table_name='diagram_mitigation_versions')
    op.drop_index(op.f('ix_diagram_mitigation_versions_id'), table_name='diagram_mitigation_versions')
    op.drop_index(op.f('ix_diagram_mitigation_versions_diagram_mitigation_id'), table_name='diagram_mitigation_versions')
    op.drop_table('diagram_mitigation_versions')
    op.drop_index(op.f('ix_diagram_threat_versions_version_id'), table_name='diagram_threat_versions')
    op.drop_index(op.f('ix_diagram_threat_versions_threat_id'), table_name='diagram_threat_versions')
    op.drop_index(op.f('ix_diagram_threat_versions_id'), table_name='diagram_threat_versions')
    op.drop_index(op.f('ix_diagram_threat_versions_diagram_threat_id'), table_name='diagram_threat_versions')
    op.drop_table('diagram_threat_versions')
    op.drop_index(op.f('ix_diagram_versions_version_number'), table_name='diagram_versions')
    op.drop_index(op.f('ix_diagram_versions_id'), table_name='diagram_versions')
    op.drop_index(op.f('ix_diagram_versions_diagram_id'), table_name='diagram_versions')
    op.drop_table('diagram_versions')
    # ### end Alembic commands ###
