"""add_threat_id_to_diagram_mitigations

Revision ID: 42d5e8ebdc8c
Revises: 837f9f5cb442
Create Date: 2026-02-13 14:33:20.442137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d5e8ebdc8c'
down_revision: Union[str, Sequence[str], None] = '837f9f5cb442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagram_mitigations', sa.Column('threat_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_diagram_mitigations_threat_id'), 'diagram_mitigations', ['threat_id'], unique=False)
    op.create_foreign_key('fk_diagram_mitigations_threat_id', 'diagram_mitigations', 'diagram_threats', ['threat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_diagram_mitigations_threat_id', 'diagram_mitigations', type_='foreignkey')
    op.drop_index(op.f('ix_diagram_mitigations_threat_id'), table_name='diagram_mitigations')
    op.drop_column('diagram_mitigations', 'threat_id')
    # ### end Alembic commands ###
