"""Initial migration with all models

Revision ID: 837f9f5cb442
Revises: 
Create Date: 2026-02-13 00:37:09.791182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837f9f5cb442'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frameworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frameworks_id'), 'frameworks', ['id'], unique=False)
    op.create_index(op.f('ix_frameworks_name'), 'frameworks', ['name'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('diagrams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('diagram_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagrams_id'), 'diagrams', ['id'], unique=False)
    op.create_index(op.f('ix_diagrams_product_id'), 'diagrams', ['product_id'], unique=False)
    op.create_table('mitigations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitigations_framework_id'), 'mitigations', ['framework_id'], unique=False)
    op.create_index(op.f('ix_mitigations_id'), 'mitigations', ['id'], unique=False)
    op.create_index(op.f('ix_mitigations_name'), 'mitigations', ['name'], unique=False)
    op.create_table('threats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threats_framework_id'), 'threats', ['framework_id'], unique=False)
    op.create_index(op.f('ix_threats_id'), 'threats', ['id'], unique=False)
    op.create_index(op.f('ix_threats_name'), 'threats', ['name'], unique=False)
    op.create_table('diagram_mitigations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagram_id', sa.Integer(), nullable=False),
    sa.Column('mitigation_id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.String(length=100), nullable=False),
    sa.Column('element_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagram_id'], ['diagrams.id'], ),
    sa.ForeignKeyConstraint(['mitigation_id'], ['mitigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagram_mitigations_diagram_id'), 'diagram_mitigations', ['diagram_id'], unique=False)
    op.create_index(op.f('ix_diagram_mitigations_id'), 'diagram_mitigations', ['id'], unique=False)
    op.create_index(op.f('ix_diagram_mitigations_mitigation_id'), 'diagram_mitigations', ['mitigation_id'], unique=False)
    op.create_table('diagram_threats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagram_id', sa.Integer(), nullable=False),
    sa.Column('threat_id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.String(length=100), nullable=False),
    sa.Column('element_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagram_id'], ['diagrams.id'], ),
    sa.ForeignKeyConstraint(['threat_id'], ['threats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagram_threats_diagram_id'), 'diagram_threats', ['diagram_id'], unique=False)
    op.create_index(op.f('ix_diagram_threats_id'), 'diagram_threats', ['id'], unique=False)
    op.create_index(op.f('ix_diagram_threats_threat_id'), 'diagram_threats', ['threat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagram_threats_threat_id'), table_name='diagram_threats')
    op.drop_index(op.f('ix_diagram_threats_id'), table_name='diagram_threats')
    op.drop_index(op.f('ix_diagram_threats_diagram_id'), table_name='diagram_threats')
    op.drop_table('diagram_threats')
    op.drop_index(op.f('ix_diagram_mitigations_mitigation_id'), table_name='diagram_mitigations')
    op.drop_index(op.f('ix_diagram_mitigations_id'), table_name='diagram_mitigations')
    op.drop_index(op.f('ix_diagram_mitigations_diagram_id'), table_name='diagram_mitigations')
    op.drop_table('diagram_mitigations')
    op.drop_index(op.f('ix_threats_name'), table_name='threats')
    op.drop_index(op.f('ix_threats_id'), table_name='threats')
    op.drop_index(op.f('ix_threats_framework_id'), table_name='threats')
    op.drop_table('threats')
    op.drop_index(op.f('ix_mitigations_name'), table_name='mitigations')
    op.drop_index(op.f('ix_mitigations_id'), table_name='mitigations')
    op.drop_index(op.f('ix_mitigations_framework_id'), table_name='mitigations')
    op.drop_table('mitigations')
    op.drop_index(op.f('ix_diagrams_product_id'), table_name='diagrams')
    op.drop_index(op.f('ix_diagrams_id'), table_name='diagrams')
    op.drop_table('diagrams')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_frameworks_name'), table_name='frameworks')
    op.drop_index(op.f('ix_frameworks_id'), table_name='frameworks')
    op.drop_table('frameworks')
    # ### end Alembic commands ###
