"""add_user_authentication_and_ownership

Revision ID: 8e428cd957df
Revises: 1e4c215959d3
Create Date: 2026-02-13 21:27:38.437778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e428cd957df'
down_revision: Union[str, Sequence[str], None] = '1e4c215959d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create users table
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    # Create default admin user (password: Admin@1234)
    # Using sa.text() with bindparams to prevent SQL injection
    admin_password_hash = '$2b$12$2XyL.cXAztDr9zHr/buwue/gmeN5cpyI0OnDMYzObJLED5NGAumLy'
    op.execute(
        sa.text(
            "INSERT INTO users (email, username, hashed_password, full_name, is_active, is_superuser) "
            "VALUES (:email, :username, :password_hash, :full_name, :is_active, :is_superuser)"
        ).bindparams(
            email='admin@acme.com',
            username='admin',
            password_hash=admin_password_hash,
            full_name='Admin User',
            is_active=True,
            is_superuser=True
        )
    )

    # Add created_by to diagrams (nullable)
    op.add_column('diagrams', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_diagrams_created_by'), 'diagrams', ['created_by'], unique=False)
    op.create_foreign_key(None, 'diagrams', 'users', ['created_by'], ['id'])

    # Add user_id to products (nullable first)
    op.add_column('products', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_user_id'), 'products', ['user_id'], unique=False)
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'])

    # Assign existing products to admin user
    op.execute("UPDATE products SET user_id = (SELECT id FROM users WHERE username = 'admin' LIMIT 1) WHERE user_id IS NULL")

    # Make user_id NOT NULL
    op.alter_column('products', 'user_id', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_user_id'), table_name='products')
    op.drop_column('products', 'user_id')
    op.drop_constraint(None, 'diagrams', type_='foreignkey')
    op.drop_index(op.f('ix_diagrams_created_by'), table_name='diagrams')
    op.drop_column('diagrams', 'created_by')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
